# I'm going to abandon panes because hyprland can use windows (and it's easier that way)
enabled_layouts splits

#splits
map ctrl+alt+h split_horizontal
map ctrl+alt+v split_vertical

#navigation
map ctrl+alt+left  focus left
map ctrl+alt+right focus right
map ctrl+alt+up    focus up
map ctrl+alt+down  focus down

#resizing
map ctrl+alt+shift+left  resize_left 5
map ctrl+alt+shift+right resize_right 5
map ctrl+alt+shift+up    resize_up 5
map ctrl+alt+shift+down  resize_down 5

#close pane
map ctrl+alt+c close
