"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:mono) \
"""

palette = "mono-light"

[palettes.mono-light]
overlay = '#1C1C28'    # background
mono_dark = '#B0B0B0'  # standard text
mono_light = '#E0E0E0' # highlights

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:mono_dark"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "


[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:mono_light"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:mono_light"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:mono)'
untracked = '[?\($count\)](bg:overlay fg:mono)'
stashed = '[\$](bg:overlay fg:mono)'
modified = '[!\($count\)](bg:overlay fg:mono)'
renamed = '[»\($count\)](bg:overlay fg:mono)'
deleted = '[✘\($count\)](bg:overlay fg:mono)'
staged = '[++\($count\)](bg:overlay fg:mono)'
ahead = '[⇡\(${count}\)](bg:overlay fg:mono)'
diverged = '⇕[\[](bg:overlay fg:mono)[⇡\(${ahead_count}\)](bg:overlay fg:mono)[⇣\(${behind_count}\)](bg:overlay fg:mono)[\]](bg:overlay fg:mono)'
behind = '[⇣\(${count}\)](bg:overlay fg:mono)'

[time]
disabled = false
format = " [](fg:overlay)[ $time 🌀 ]($style)[](fg:overlay) "
# style = "bg:iris fg:mono_light bg:overlay"
style = "fg:mono_light bg:overlay"
time_format = "%I:%M%p"
use_12hr = true

[username]
disabled = false
format = " [](fg:overlay)[ ⚡ $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:mono_light"
style_user = "bg:overlay fg:mono_light"
# Languages

[c]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:mono_light"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = '🅒 '
