[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin mount"

# if it finds a match, it'll automatically enter the directory.
# so watch out when typing
[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Enter directory if it finds a match (automatically)"

# paste into directories without going in them
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD" 

# unfortunately I can't use this

[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

#[[mgr.prepend.keymap]]
#on   = "f"
#run  = "plugin jump-to-char"
#desc = "Jump to char"

# does NOT work
#[[mgr.prepend.keymap]]
#on   = "z"
#run  = "z"
