Completion:
  HeaderInsertion: Never
  AllScopes: False

Index:
  StandardLibrary: No

CompileFlags:
  Add:
    - -Wpedantic
    - -Wall
    - -Wextra
    - -Wshadow
    - -Wfloat-equal
    - -Wstrict-overflow=2
    - -Wmissing-declarations
    - -Wredundant-decls
    - -Wundef
    - -Wshadow=local
    - -Wformat=2
    - -Wstack-protector
    - -Wstrict-aliasing=2
    - -Wnull-dereference
    - -Wabstract-vbase-init
    - -Wnon-virtual-dtor
    - -Woverloaded-virtual
    - -Wno-empty-translation-unit
    - -Werror

---

If:
  PathMatch: .*\.(cpp|cc|hpp)$
CompileFlags:
  Add:
    - -std=c++23
    - -xc++
    - -Wweak-vtables

---

If:
  PathMatch: .*\.(c|h)$
CompileFlags:
  Add:
    - -std=c17
    - -xc
    - -Wmissing-prototypes

# InlayHints:
#   BlockEnd: false
#   Designators: true
#   Enabled: true
#   ParameterNames: true
#   DeducedTypes: true
#   DefaultArguments: false
#   TypeNameLimit: 24
